name: Land ghstack PRs
on:
  repository_dispatch:
    types: [land-command]

jobs:
  ghstack_land:
    name: ghstack Land
    runs-on: ubuntu-latest
    steps:
    - name: Show Environment Variables
      run: env
    - name: Show Github Object
      run: |
        cat <<'EOF'
        ${{ toJson(github) }}
        EOF
    - name: Show Github Event Path Json
      run: 'cat $GITHUB_EVENT_PATH || true'
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GHSTACK_PAT }}
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Check Current CI Status
      run: |
        pip install requests ghstack
        .github/workflows/scripts/ghstack-perm-check.py <<'EOF'
        ${{ toJson(github) }}
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GHSTACK_PAT }}
    - name: Land It!
      run: |
        git config --global user.email "foo@foo.com"
        git config --global user.name "ghstack bot"
        cat <<EOF > ~/.ghstackrc
        [ghstack]
        github_url = github.com
        github_oauth = $GITHUB_TOKEN
        github_username = chillee
        remote_name = origin
        EOF
        ghstack land "${{ github.event.client_payload.pull_request.html_url }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GHSTACK_PAT }}