name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: Slash Command Dispatch - Repo - Write
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.GHSTACK_PAT }}
        reaction-token: ${{ secrets.GHSTACK_PAT }}
        issue-type: pull-request
        permission: write
        commands: |
          land
